- topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
  ign_type_name: ignition.msgs.Clock
  direction: GZ_TO_ROS

- topic_name: /scan
  ros_type_name: sensor_msgs/msg/LaserScan
  ign_type_name: ignition.msgs.LaserScan
  direction: GZ_TO_ROS

- topic_name: /cmd_vel
  ros_type_name: geometry_msgs/msg/Twist
  ign_type_name: ignition.msgs.Twist
  direction: ROS_TO_GZ

- topic_name: /odom
  ros_type_name: nav_msgs/msg/Odometry
  ign_type_name: ignition.msgs.Odometry
  direction: GZ_TO_ROS

- topic_name: /tf
  ros_type_name: tf2_msgs/msg/TFMessage
  ign_type_name: ignition.msgs.Pose_V
  direction: GZ_TO_ROS

- topic_name: /joint_states
  ros_type_name: sensor_msgs/msg/JointState
  ign_type_name: ignition.msgs.Model
  direction: GZ_TO_ROS
